DICOM SR and DICOM SEG import export [sc-5791]
mdai/mdai-client-py pull request #53
Opened 2023-08-18 02:09 UTC by wzhlifelover

-  src code modified from summer intern Dyllan's [work](https://github.com/spike-h/mdai/tree/main) 
- New functions allow SR export, SEG export from MD.ai annotations and SR import into MD.ai annotation note

Examples:
### SR export
exporter = mdai.SR_SEG_utils.SR_SEG_Export('SR', annotation_file, metadata_file)
Successfully exported DICOM SR files into SR_Output
![Screen Shot 2023-08-17 at 10 06 33 PM](https://github.com/mdai/mdai-client-py/assets/49887319/9ebc0a9f-4469-48f0-9a18-0d9094346f74)

### SEG export
exporter = mdai.SR_SEG_utils.SR_SEG_Export('SEG', annotation_file, metadata_file)
Successfully exported DICOM SEG files into SEG_Output
![Screen Shot 2023-08-17 at 10 05 09 PM](https://github.com/mdai/mdai-client-py/assets/49887319/dd24ea22-0408-4c4e-9e45-cdc4ef076acb)

### SR import
mdai_client.import_SR(file_path="DICOM_SR_D_2NnevZ_1.2.826.0.1.3680043.8.498.10501549244263206170119288752475799160_annotator_1.dcm", dataset_id="D_2NnevZ", project_id = "L1Np
nQBv", label_id="L_QRzGlQ")
Importing 1 annotations into project L1NpnQBv, dataset D_2NnevZ...                                  
Successfully imported 1 / 1 annotations into project L1NpnQBv, dataset D_2NnevZ. 
![Screen Shot 2023-08-17 at 10 07 09 PM](https://github.com/mdai/mdai-client-py/assets/49887319/42e2ad1b-5ece-46bf-a7e5-46ca82998395)

2023-08-18 02:19 UTC, transcranial requested changes
Module should be called `dicom_utils`. Combining SR with SEG is a bit awkward. How about creating 2 separate classes that inherits a common class?

2023-08-18 02:19 UTC, transcranial commented on mdai/__init__.py
> +from .utils import SR_SEG_utils
Module names should have short, all-lowercase names (see [pep8](https://peps.python.org/pep-0008/#package-and-module-names)).

2023-08-18 04:54 UTC, wzhlifelover commented
Reconstructed `dicom_utils` and created two child classes inheriting `DicomExport` Class

> Module should be called `dicom_utils`. Combining SR with SEG is a bit awkward. How about creating 2 separate classes that inherits a common class?

2023-08-18 19:52 UTC, transcranial requested changes

2023-08-18 19:52 UTC, transcranial commented on mdai/client.py
> +    def iterate_content_seq(self, content, content_seq_list):
This should be factored out -- it does not belong here logically.

2023-08-21 21:40 UTC, transcranial approved these changes

2023-08-21 21:40 UTC, merged